networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  database-server:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "8091:8091"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
